### ISSUE TITLE
Installing fails on google collab

### ISSUE THREAD

**Issue by noDGodyaev** [ev-br/mc_lib#15] opened 2021-02-26 16:10 UTC
Все попытки установить тут:
[**collab**](https://colab.research.google.com/drive/1EZT2GA-vElPzl0__soKw26SWLsGks891?usp=sharing)

**Comment by ev-br** [comment] 2021-02-26 16:25
Confirmed. The gist seems to be that it fails to find pxd files from numpy:

```
!python setup.py

Cythonizing sources
mc_lib
Processing mc_lib/rndm.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# cython: language_level=3

from numpy.random cimport bitgen_t
^
------------------------------------------------------------

mc_lib/rndm.pxd:3:0: 'numpy/random.pxd' not found
```

Same issue when running `pip install -v`.

**Comment by ev-br** [comment] 2021-02-26 16:29
Thanks for the report. TBH, I've no idea. Seems to be some distutils/setuptools weirdness which I did not properly account for.

**Comment by ev-br** [comment] 2021-03-13 16:48
NB: https://github.com/ev-br/mc_lib/commit/e62dc892bb42d40e9a5681af3a133f21de02114d did not fix it, still fails to find numpy.random pxd-s

**Comment by ev-br** [comment] 2021-06-25 15:22
@rgommers here's the headscratcher I asked about on scipy community zoom call. Would really appreciate pointers to what this might be : it does find numpy/random.pxd from a top-level ipython %cython cell, but fails to find it when cimporting from a pxd

**Comment by rgommers** [comment] 2021-06-25 15:40
This works perfectly fine in a `scipy-dev` conda environment (as created from the `environment.yml` file in the scipy repo), and the `setup.py` and `tools/cythonize.py` code looks fine to me. So I think this is specific to Colab/Jupyter. I'm not quite sure what that does when you run a command with `!python ...` or `!pip ...`. Maybe it runs things in a subprocess where the underlying env isn't properly activated or something like that?

**Comment by rgommers** [comment] 2021-06-25 15:43
Oh, or it's simpler: you have neither a `pyproject.toml` file nor `install_requires` in `setup.py`, so `numpy` is simply not installed in that Colab linked in the first issue.

**Comment by ev-br** [comment] 2021-06-25 19:23
Thanks Ralf! I tried following your suggestion: add `install_requires` (it should install or upgrade the numpy, correct?), run in a fresh venv, but no dice. Still doing something wrong, it seems?

The diff:
```
$ git diff
diff --git a/setup.py b/setup.py
index 4237d58..3d23c55 100644
--- a/setup.py
+++ b/setup.py
@@ -92,6 +92,8 @@ def setup_package():
               license=LICENSE,
               configuration=configuration,
               package_data={PACKAGE_NAME : ["rndm.pxd"],},
+              install_requires=['numpy>=1.19.5'],
+              setup_requires=['numpy>=1.19.5'],
               zip_safe=False,
               classifiers=[
                 'Development Status :: 4 - Beta'
```

And the build log:

```
$ pip install -e . -v
Using pip 21.1.2 from /home/br/.venvs/mc_lib_venv/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-sh9vzxmy
Created temporary directory: /tmp/pip-req-tracker-lowwmami
Initialized build tracking at /tmp/pip-req-tracker-lowwmami
Created build tracker: /tmp/pip-req-tracker-lowwmami
Entered build tracker: /tmp/pip-req-tracker-lowwmami
Created temporary directory: /tmp/pip-install-9nv8yihs
Obtaining file:///home/br/sweethome/proj/mc_lib
  Added file:///home/br/sweethome/proj/mc_lib to build tracker '/tmp/pip-req-tracker-lowwmami'
    Running setup.py (path:/home/br/sweethome/proj/mc_lib/setup.py) egg_info for package from file:///home/br/sweethome/proj/mc_lib
    Created temporary directory: /tmp/pip-pip-egg-info-qnqscspk
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/br/sweethome/proj/mc_lib/setup.py", line 114, in <module>
        setup_package()
      File "/home/br/sweethome/proj/mc_lib/setup.py", line 64, in setup_package
        from numpy.distutils.core import setup
    ModuleNotFoundError: No module named 'numpy'
WARNING: Discarding file:///home/br/sweethome/proj/mc_lib. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
```

**Comment by ev-br** [comment] 2021-06-25 19:54
gh-18 swaps setuptools.setup for numpy.distutils.setup and declares `install_requires`. Does not work yet: in a clean venv without preinstalled numpy & cython, it does not install them; if they are already installed, the build succeeds.

**Comment by rgommers** [comment] 2021-06-25 20:56
Ah maybe this: `setup_requires` may be malfunctioning, because that always used to invoke `easy_install` and that has now finally been removed from `setuptools` (replaced by `pip`). `pip` never supported `setup_requires` directly. So what's happening here is a sort of `pip`ception: `pip install mypackage` doesn't understand a thing, call `setuptools`, which then calls `pip` again in a subprocess to install the build dependency. **But** you are calling `generate_cython` _before_ `setuptools` gets a chance to run its `setup()` which would install `numpy`.

I get it:) And it's godawful:(

The correct/modern way to do this is adding a `pyproject.toml` file with build dependencies.

**Comment by rgommers** [comment] 2021-06-25 20:59
I need a beer now, this hurt my head thinking about it.....

**Comment by ev-br** [comment] 2021-06-25 22:10
Ouch. What a heinous mess. Ouch. I need a beer just trying to read that single-paragraph summary. No, am not going to touch `install_requires` with a barge pole.

A beer's on me next time we're in the same city :-).

**Comment by ev-br** [comment] 2021-06-25 22:19
Adding `pyproject.toml` actually seems to work some, https://github.com/ev-br/mc_lib/pull/19.
The costs are (i) have to drop python 3.5 (not an unbearable loss, but heck why) and (ii) the build log (`pip install -v`)  is four freaking thousand lines.
Not sure yet if it's worth it TBH.

@noDGodyaev could you try testing https://github.com/ev-br/mc_lib/pull/19 on Colab? The incantation is, I believe, `!pip install git+https://github.com/ev-br/mc_lib.git@pyproject_toml` or some such.

**Comment by rgommers** [comment] 2021-06-26 08:23
> The costs are (i) have to drop python 3.5 (not an unbearable loss, but heck why)

This is unrelated to `pyproject.toml`. You're using `numpy>=1.19.5` (because you need it for the new random API), and `1.19.0` had already dropped Python 3.5. So it would never have worked.

> and (ii) the build log (pip install -v) is four freaking thousand lines.

Yeah, `pip` is terrible at logging. Hence `-v` isn't default - `pip install mc_lib` will be almost completely silent:)

**Comment by ev-br** [comment] 2021-06-27 15:58
> and 1.19.0 had already dropped Python 3.5. So it would never have worked.

Except that it did build and pass smoke-testing on CI. Meaning that it was only using a tiny speck on the numpy API surface, which happened to work on python 3.5 and it would fail randomly if used more. I'm not very happy about the velocity of python itself, but my unhappiness is moot anyway :-).

> pip install mc_lib will be almost completely silent:)

Indeed it is. Even if cython compilation fails somehow, it still is almost completely silent :-). 

This whole "compile in a subprocess" thing that cythonize does is not very user-friendly, and I've a few users whose only python experience is pure python scripting, so they are rather likely to have to problems building stuff. Not much I can do here as well.

Anyway, thanks a whole lot Ralf! 
I suspect we'll try pinging you further on when moving this stuff to meson. Hope that way is a little less weird (I'm still recovering from an unexpected learning of `easy_install` abominations sneaking into play :-)).

**Comment by noDGodyaev** [comment] 2021-06-29 14:03
Tried to [install ](https://colab.research.google.com/drive/1ieiEzmHpyRUwH9sdtaI6RWZz2OXytNK5?usp=sharing )from pyproject_toml branch in collab: `!pip install git+https://github.com/ev-br/mc_lib.git@pyproject_toml.` It successfully installed and worked fine.


    %%cython

    from mc_lib.rndm cimport RndmWrapper

    cdef RndmWrapper rndm = RndmWrapper((1234, 0))
    print(rndm.uniform())

    import sys
    print(sys.version)

Output:

    0.9766997666981422
    3.7.10 (default, May  3 2021, 02:48:31) 
    [GCC 7.5.0]

**Comment by ev-br** [comment] 2021-06-29 15:05
Great, thanks for checking @noDGodyaev , thanks Ralf for the pointer!

**Comment by ev-br** [comment] 2021-06-29 15:07
Fixed by gh-19, closing

**Closed by ev-br** 2021-06-29 15:07 UTC
Labels: bug, build issues
